### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by S-HongJie** [dinghuang/91660-java#1]
![U{PM~ XI%X98AK6}XH`5Q~I](https://user-images.githubusercontent.com/66894532/166107947-e59623cf-954f-42b6-9c17-1b21a69142cc.png)
$ sh start.sh
start.sh: line 3: cd: /root/ticket/testNGExample-master: No such file or directory
start.sh: line 4: /root/ticket/logs/info.log: No such file or directory
出现了这个 想问问怎么解决

**Comment by dinghuang** [comment]
换了一种新的实现方式，不用这种了
