### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by S-HongJie** [dinghuang/91660-java#2]
![1651852845(1)](https://user-images.githubusercontent.com/66894532/167169885-3a544eb5-49de-4a4e-a3fc-0f92586e3160.png)
![1651852868(1)](https://user-images.githubusercontent.com/66894532/167169927-c1b05054-33f2-4352-ab90-4e4c3c06ac0d.png)

![1651852902](https://user-images.githubusercontent.com/66894532/167169934-01771ac7-7d30-4b89-a943-14ef7154a61d.png)
在调试过程中 出现这个 想问下是否我在设置中出错 userInfo.setAddress("");
                userInfo.setAddressId("");这两个是填写哪个参数

**Comment by dinghuang** [comment]
这个你看一下todo
